### ISSUE TITLE
Logformat + Loki

### ISSUE THREAD

**Issue by imclint21** [3proxy/3proxy#1029]
Hi,

I want to use 3proxy in Loki, so I forge a custom format like this:

```
logformat "timestamp=%t service=%N service_port=%p error=%E user=%U client_ip=%C client_port=%c target_ip=%R target_port=%r bytes_out=%O bytes_in=%I hops=%h query=%T"
```

But because of the space in the query its break the parsing of Loki
<img width="179" alt="image" src="https://github.com/3proxy/3proxy/assets/5221349/ba43fc39-139b-409e-b092-6d305d80f44d">

I try to escape the quote like that: query=\"%T\"" but not work too, any idea @z3APA3A how to escape logs?

**Comment by z3APA3A** [comment]
Check https://3proxy.ru/doc/man3/3proxy.cfg.3.html

1. Use double `""` for quote character inside string (BASIC style quoting). That is, use `query=""%T""`
2. Use -+ construction to filter characters inside logformat, e.g. `"-""+_G...."` changes `"` to `_`
3. Use `%#T `construction instead of `%T` to ouput part of request. For "GET http://host/path HTTP/1.0" 
%1T = GET
%2T = http://host/path
%3T = HTTP/1.0
etc

**Comment by imclint21** [comment]
Awesome,

Just a little issue, with the same log format:

```
logformat " timestamp=%t"
```

I noticed that sometimes the first t is truncated, its why I added a space, any thoughts about this?

**Comment by imclint21** [comment]
There also a problem, when using:

```
logformat "hops=%h method=""%1T"""
```

it's give Get with 2 t

```
hops=0 method="GETT"
```

**Comment by imclint21** [comment]
@z3APA3A

**Comment by z3APA3A** [comment]
Check logformat description in https://3proxy.ru/doc/man3/3proxy.cfg.3.html

First character in logformat indicated time format (L for local, G for GMT)
Use %1-1T instead of %1T.
