### ISSUE TITLE
Logging  (src/dst ips and Outgoing/Target ip addresses ) in log file 

### ISSUE THREAD

**Issue by Bitrion** [3proxy/3proxy#1049]
Hello ,

Im running 
3proxy tiny proxy server 3proxy-0.9.3 ()

Im trying to have logs as :

Date/Time  - SrcIP  - SrcPort -  DstIp(ip listening of 3proxy) -  Dst port ( Port where 3proxy listen)-  HTTPResponceCode- (Websites or ip  being targeted )(Outgoing ip address of 3proxy that will go out) ( ip address of targetted website) (Size of connection in Bytes)

Im trying with the logformat :

logformat "L%d-%m-%Y %H:%M:%S %p %E %I %h %O %R %n %c"

But im not getting result looking for !

im getting below :

23-06-2024 12:25:55 38825 00004 0 0 0 12.13.180.4 12.13.180.4 22534

Which is far from what im looking for .

Hope to guide me with some help to achieve my goal .
Thanks

**Comment by z3APA3A** [comment]
Check `logformat` in manual https://3proxy.ru/doc/man3/3proxy.cfg.3.html, your results match to your format string.

in most cases it's impossible to log HTTP code, because modern sites use encrypted https, and http handshake is not visible to proxy. You can log 3proxy error code (%E) or just use "200" if you need compatibility with HTTP log format.
