### ISSUE TITLE
random parent

### ISSUE THREAD

**Issue by iwyz0** [3proxy/3proxy#1088]
Hello

daemon
timeouts 1 5 30 60 180 1800 15 60
maxconn 35000
nscache 65535
log /var/log/3proxy/user.log D
logformat "L%t. %N%p %E %U %C:%c %R:%r %O %I %h %T"
flush
auth strong iponly
users user:CL:1234567
allow user
parent 100 http xx.xx.xx.xx 50119 user pass
parent 100 http xx.xx.xx.xx 50157 user pass
parent 100 http xx.xx.xx.xx 50208 user pass
parent 100 http xx.xx.xx.xx 50246 user pass
parent 100 http xx.xx.xx.xx 52023 user pass
parent 100 http xx.xx.xx.xx 52078 user pass
parent 100 http xx.xx.xx.xx 52105 user pass
parent 100 http xx.xx.xx.xx 52107 user pass
parent 100 http xx.xx.xx.xx 52160 user pass
parent 100 http xx.xx.xx.xx 52250 user pass

I added 10 IPs here. We want the request to go to a random IP or a sequential IP equally in each request. Can we write something else instead of 100 here? So, when I add 150 ip proxy, I have to calculate and determine the number each time, which seems not very practical.

**Comment by iwyz0** [comment]
Hello
Additionally, when I add 1000 IP addresses, I have to say parent 1.
When I say add 2000 ip, how many parent should we say under normal conditions?

**Comment by z3APA3A** [comment]
3proxy is not intended and is not optimized for large ACLs and is not intended to be used as rotaring proxy with huge lists, it lacks functionality like parent health checking.

> When I say add 2000 ip, how many parent should we say under normal conditions?

This configuration can be implemented with cascading proxies (to have 2000 parents at first step select one of 40 local parent proxies  with 50 external parent proxies for each local parent proxy.

> I have to calculate and determine the number each time, which seems not very practical.

configuration like this is usually generated by script rather than created by hands
