### ISSUE TITLE
3Proxy does not change the IP once keep-alive running

### ISSUE THREAD

**Issue by Al-Bsharat** [3proxy/3proxy#751]
Hello.
We used these 3proxy configs.

> daemon
> nserver 127.0.0.1
> timeouts 1 5 30 60 5 5 15 60
> maxconn 120000
> pidfile /home/3proxyProfile2/3proxy.pid
> noforce
> auth iponly
> allow  * * * * *
> parent 1000 extip XXXX::/29 0
> proxy -6 -n -a -s0 -p12001 -i127.0.0.1

When the app sends too many requests with keep-alive haproxy will use the same IP from that range always, which is not expected.
How to solve that?

**Comment by z3APA3A** [comment]
"keep-alive" requests are requests sent via same connection, TCP connection can not change it's IP. If you want every request to establish new connection either disable keep-alive on the client side or rewrite keep-alive on the proxy side (PCREPlugin). For https rewriting is not trivial, because traffic is encrypted and requires certificate spoofing (SSLPlugin).
