### ISSUE TITLE
Some sites do not work correctly with IPV6

### ISSUE THREAD

**Issue by Bolshaksa** [3proxy/3proxy#776]
Some sites do not work correctly with IPV6
For example, fc2.com gives an error 502 or ERR_TUNNEL_CONNECTION_FAILED (if you specify a connection via https in the address bar).
Because the output to network is through the tunnel, then the input address is ipv4 with the specified port for forwarding to ipv6. This ipv4 address is given to the website in request headers and probably for this reason i don`t get answer.
If someone faced, tell me how you solved this problem?
I will also be grateful if you tell me how to make the same ipv6 address through which I access the network be given in the request headers to the website?

**Comment by z3APA3A** [comment]
Under this configuration proxy uses IPv4 by default. You an use
e.g.
proxy -64
Also, there is no 'server' command, probably you mean 'nserver'.

**Comment by z3APA3A** [comment]
For IPv6 you would also want to use `nscache6` in addition to nscache

**Comment by Bolshaksa** [comment]
Thanks, I solved the problem of opening some websites through ipv6.
I spent the whole night reading the manuals on your site and finally made such a design (the IP address has been changed).

**proxy -6 -s0 -64 -a -p30000 -i5.25.34.103 -e2231:320:2a5b:32a8:f5d2:4a5b:b342:121a**

I have added many lines - each line with different port (30001, 30002, 30003 and etc..) for 1 ipv6 address

But in the end I got another problem. Websites see my ipv4 address, which makes it useless to use a proxy. I am using ipv6 proxy through ipv4 (via tunnelbroker).
If I go to the whoer.net website - a service for information about the ip address, which was not previously opened through ipv6 (after the edits indicated above, it began to open), then the site shows my ipv4 address 5.25.34.103 ... The same with other sites - they see my original ipv4 used for the tunnel enter (addrress of my server where 3proxy is installed).

Is there any way to hide my ipv4 address from websites?

**Comment by z3APA3A** [comment]
Probably, you misunderstand how IPv4/IPv6 work. IPv6 is not VPN, IPv4 and IPv6 are two different networks. Site can have IPv4 address, IPv6 address or both. In the case site has no IPv6 address it's not reachable via IPv6. You can configure 3proxy to only use IPv6  ( -6 ), in this case sites without Pv6 like fc2.com are not reachable, and it's expected behavior. You can configure 3proxy to fallback to IPv4 for sites without IPv6 address. In this case 3proxy IPv4 address will be seen by the site, and it's expected behavior. You can not contact IPv4 site via IPv6 network.

**Comment by Bolshaksa** [comment]
Ok, now is clear - thank you
